#!/usr/bin/env python3
"""
gen-ec-registry — emit canonical EC registry from test-vectors.md
==================================================================
Reads test-vectors.md and emits a single canonical EC registry file at
.factory/specs/prd-supplements/ec-registry.md that BC edge-case tables
can be validated against.

The registry is marked with BEGIN/END GENERATED markers so the surrounding
prose (header, footnotes) is never clobbered on regeneration.

Idempotent: running twice produces identical output.

IMPORTANT: This generator does NOT modify test-vectors.md. It reads from it
and writes a NEW ec-registry.md. The BC edge-case tables remain unchanged;
check-ec-injectivity.py validates them against this registry.

Usage:
  python3 gen-ec-registry.py [--dry-run]
"""
import re
import sys
from pathlib import Path
import spec_lint_primitives as slp

REPO = slp.find_repo_root(start=Path(__file__).resolve().parent)  # honors SPEC_LINT_REPO_OVERRIDE
SPECS = REPO / ".factory" / "specs"
TV_FILE = SPECS / "prd-supplements" / "test-vectors.md"
OUTPUT = SPECS / "prd-supplements" / "ec-registry.md"

GENERATED_HEADER = "<!-- BEGIN GENERATED: ec-registry -->"
GENERATED_FOOTER = "<!-- END GENERATED: ec-registry -->"

ARTIFACT_HEADER = """\
---
document_type: prd-supplement
supplement_type: ec-registry
level: L3
status: generated
producer: scripts/spec-lint/gen-ec-registry.py
traces_to: .factory/specs/prd-supplements/test-vectors.md
note: >
  This file is GENERATED from test-vectors.md. Do not edit by hand.
  Regenerate with: just spec-gen (or python3 scripts/spec-lint/gen-ec-registry.py)
---

# EC Registry: Canonical Edge Case Definitions

> Source of truth: `prd-supplements/test-vectors.md`.
> This registry is generated by `gen-ec-registry.py` for use by `check-ec-injectivity.py`.
> Each EC-NNN must appear here exactly once (or be in the holdout pool).
> BC edge-case tables cite these IDs and their descriptions must match.
>
> Holdout ECs are NOT in this file — they are in `.factory/holdout-scenarios/`.

"""


def parse_tv_ec_rows(path: Path) -> list[tuple[str, str, str, str]]:
    """
    Parse test-vectors.md for all EC references.
    Returns list of (ec_id, tv_id, description, verdict).
    """
    rows: list[tuple[str, str, str, str]] = []
    seen: set[str] = set()

    for lineno, line in enumerate(slp.cm_splitlines(path.read_text(encoding="utf-8")), 1):
        # Skip HOLDOUT WARNING block
        if "HOLDOUT" in line.upper():
            continue
        # Match TV table row: | TV-NNN | EC-NNN | desc... | flags | exit | verdict | reason |
        m = re.match(
            r"^\|\s*(TV-[\w]+)\s*\|\s*(EC-\d{1,4}[a-z]?)\s*\|\s*(.+?)\s*\|"
            r".*?\|\s*(\d+|n/a)\s*\|\s*(.+?)\s*\|",
            line,
        )  # EC grammar aligned with slp.EC_TOKEN_RE: 1–4 digits, optional letter (BI-044)
        if m:
            tv_id = m.group(1)
            ec_id = m.group(2)
            desc = m.group(3).strip()
            verdict = m.group(5).strip()
            if ec_id not in seen:
                seen.add(ec_id)
                rows.append((ec_id, tv_id, desc, verdict))

    return sorted(rows, key=lambda r: (int(re.search(r"\d+", r[0]).group()), r[0]))


def generate_registry_block(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [
        "## EC Registry Table",
        "",
        "| EC ID | TV ID | Description | Expected Verdict/Exit |",
        "|-------|-------|-------------|----------------------|",
    ]
    for ec_id, tv_id, desc, verdict in rows:
        # Truncate long descriptions for table readability
        short_desc = desc[:80] + "..." if len(desc) > 80 else desc
        short_verdict = verdict[:40] + "..." if len(verdict) > 40 else verdict
        lines.append(f"| {ec_id} | {tv_id} | {short_desc} | {short_verdict} |")

    lines.append("")
    lines.append(f"*{len(rows)} canonical EC definitions extracted from test-vectors.md.*")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    dry_run = "--dry-run" in sys.argv

    if not TV_FILE.exists():
        print(f"ERROR: test-vectors.md not found at {TV_FILE}")
        return 2

    rows = parse_tv_ec_rows(TV_FILE)
    if not rows:
        print("ERROR: No EC rows found in test-vectors.md")
        return 2

    generated_block = generate_registry_block(rows)

    if OUTPUT.exists():
        existing = OUTPUT.read_text(encoding="utf-8")
        # Replace just the generated region
        new_content = re.sub(
            rf"{re.escape(GENERATED_HEADER)}.*?{re.escape(GENERATED_FOOTER)}",
            f"{GENERATED_HEADER}\n{generated_block}{GENERATED_FOOTER}",
            existing,
            flags=re.DOTALL,
        )
        if new_content == existing:
            print(f"No changes needed: {OUTPUT} is already up to date")
            print(f"Registry contains {len(rows)} canonical EC definitions")
            return 0
    else:
        # Create new file
        new_content = (
            ARTIFACT_HEADER
            + GENERATED_HEADER + "\n"
            + generated_block
            + GENERATED_FOOTER + "\n"
        )

    if dry_run:
        print("-- DRY RUN: would write --")
        print(new_content[:500])
        print(f"... ({len(new_content)} chars total, {len(rows)} EC entries)")
        return 0

    OUTPUT.write_text(new_content, encoding="utf-8")
    print(f"Generated: {OUTPUT}")
    print(f"  {len(rows)} canonical EC definitions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
